### ISSUE TITLE
Question: RectangleShapeMorph or Shaped?

### ISSUE THREAD

**Issue by Kirtai** [Cuis-Smalltalk/Cuis-Smalltalk-UI#12]
I just saw that RectangleShapeMorph and CircleShapeMorph have been added. Would replacing "Shape" with "Shaped" fit better?

**Comment by KenDickey** [comment]
Does a RectangleShapeMorph instance have a
  rectangle shape
or a
 rectangle shaped 
?

I am not sure the $d would add information or make more natural usage.
