### ISSUE TITLE
UI-Shapes show Halo error in addPointHandle: 

### ISSUE THREAD

**Issue by rcpacheco** [Cuis-Smalltalk/Cuis-Smalltalk-UI#69]
Using the latest Cuis-Smalltalk-Dev image Cuis6.0-5542.image with the latest Core Update (5588-Symbol-value) as of today, 2022-12-18 with ,  when trying to get the Halo of a RectangleShapeMorph,  I get the error shown in the image. 
Seems to me that the command: self class haloPointIcon is returning nil, therefore it does not recognize the extents message.

![ui_shapes_issue](https://user-images.githubusercontent.com/845725/206532321-352750b9-f4cf-4726-9d7a-6449b6f0f8dd.png)

The same happens with at least with the BezierCubicMorph, BezierQuadraticMorph, CircleShapeMorph and the LineShapeMorph.

**Comment by KenDickey** [comment]
On 2022-12-08 10:11, Ricardo Pacheco wrote:

> Using the latest Cuis-Smalltalk-Dev image Cuis6.0-5542.image with the 
> latest Core Update (5588-Symbol-value) as of today, 2022-12-18 with , 
> when trying to get the Halo of a RectangleShapeMorph, I get the error 
> shown in the image.

I could not reproduce this, but found uses of Utf8{String|Symbol} in 
Cuis-Smalltalk-UI

Now updated are:
  tools/Morphic-MetaProperties.pck.st
  lib/UI-Panel.pck.st

Please pull and try again.

-KenD

**Comment by rcpacheco** [comment]
Thanks a lot! I reinstalled Cuis again and both UI-Components and UI-Tools and now the Halo is properly displayes for all the Morphs.

**Comment by rcpacheco** [comment]
As a side effect now I'm able to see properly the MetaProperties also, thanks !!
