### ISSUE TITLE
Crash upon changing LabelMorph emphasis: highBit not defined for negative Integers 

### ISSUE THREAD

**Issue by rcpacheco** [Cuis-Smalltalk/Cuis-Smalltalk-UI#70]
I created a Label Morph, Changed its emphasis to bold and Italic, then clicked Accept.
Then tried to edit again the emphasis, an the first thing I notticed is that the propper values where not selected.
Second, I unselected the all but the b0old checkboxes and clicked Accept.
After that I got the following two Error debug windows:

![image](https://user-images.githubusercontent.com/845725/206612476-3163b5f8-3f64-411b-a44a-736b9689dacf.png)

**Comment by rcpacheco** [comment]
Thanks a lot, the fix did the trick!!
I reinstalled everything from cero because After the update I got the message inthe Transcript that there was a newer version of MetaProperties and others, but I did not knew how to update them.

Is this the right botton to click?
![image](https://user-images.githubusercontent.com/845725/206813750-531bbb14-0035-4a54-864d-92ec5fa0c30c.png)

**Comment by KenDickey** [comment]
On 2022-12-09 15:56, Ricardo Pacheco wrote:

> Thanks a lot, the fix did the trick!!
> I reinstalled everything from cero because After the update I got the 
> message inthe Transcript that there was a newer version of 
> MetaProperties and others, but I did not knew how to update them.
> 
> Is this the right botton to click?

Nope.  As the tool tip notes, this allows one to select a Fearure 
Requirement and update this to the currently loaded package version for 
that feature.  For example, the recent stuff I pushed updated the base 
system requirement to version 5588.  Older versions of the UI-*.pck.st 
would work with older Cuis versions, but we want to keep up with base 
and package versions as code evolves forward.

Feature Requirements are not perfect, but nothing beats having basic 
checks.


The way I update a packaged Feature is to use the File List to select it 
and file it in.

One could make an argument for an easy way to update stale code, but the 
best way is really to start with a clean image and require+load afresh.  
The scan on update lets one know some code has been updated and allows 
you to save/fileout some work to reload into a fresh environment without 
loss of work.

You are still in the driver's seat.  The intent is to clue people in to 
something which may require attention.

No subsitute for thought and decisions.

Good on ya,
-KenD

**Comment by rcpacheco** [comment]
Thanks a lot for taking the time to writhe the explanation. It is very clear and usefull.

**Comment by KenDickey** [comment]
And thanks much for exploring Cuis and reporting when things go strange!

We are, all of us, trying to make Cuis better, and continuous update requires continuous testing.

Your use and suggestions are very welcomed!

Good on ya,
-KenD
