### ISSUE TITLE
Error while trying to open the borderWith

### ISSUE THREAD

**Issue by rcpacheco** [Cuis-Smalltalk/Cuis-Smalltalk-UI#71]
While playing with the color selection menues I ran into an error that is not easy to replicate.
Sometimes it happens, sometimes not.

1. I  crete an EllipseMorph, open its halo menu and pin it.
1. Then I change the color property by selecting the  CSS3 named colors. 
1. Sometimes, if I try to edit the borderWith it crashes. Sometimes not.
1. If it did not crash, I can drop a color in the borderWith, get a red X, Then try to edit it and it crashes.
![borderWith_error](https://user-images.githubusercontent.com/845725/206683197-f540e97e-e34f-439c-a5b2-bdaf53ff97d8.png)

I'm using Windows 10, with locale es-MX and an updated Cuis v6 - 5588.

**Comment by KenDickey** [comment]
On 2022-12-09 02:44, Ricardo Pacheco wrote:

> While plating with the color selection menues I ran into an error that 
> is not easy to replicate.
> Sometimes it happens, sometimes not.
> 
> * I crete an EllipseMorph, open its halo menu and pin it.
> * Then I change the color property by selecting the CSS3 named colors.
> * Sometimes, if I try to edit the borderWith it crashes. Sometimes not.

This appears to me to be the SignMorph problem.  It is easy to start 
dragging a SignMorph when one means to click.  The debug screen shows 
SignMorph.

Please try to reproduce with current.

Thanks much for testing and reporting!!
-KenD

**Comment by rcpacheco** [comment]
You've done a great job!! Thanks a lot!
