### ISSUE TITLE
Error while trying to drag object position from the menu

### ISSUE THREAD

**Issue by rcpacheco** [Cuis-Smalltalk/Cuis-Smalltalk-UI#72]
While trying to drag object position from the menu, as you do in your Cuis Smalltalk: Color 1 UI Part 1  ( 8:45 minute) I got an error at  the moment that I move the cursor. The cursos changes to a box with an X, as shown:

![image](https://user-images.githubusercontent.com/845725/206686917-67bb5e36-cd76-43ed-b5bd-17c65d6d33e6.png)

![image](https://user-images.githubusercontent.com/845725/206686618-6c813e6d-3b5f-410d-bf41-fef045dbc77f.png)

I'm using Windows 10, with locale es-MX and an updated Cuis v6 - 5588.

**Comment by KenDickey** [comment]
On 2022-12-09 02:59, Ricardo Pacheco wrote:

> While trying to drag object position from the menu,

I believe the update to SignMorph in UI-DragAndDrop package fixes this.

Please retest now.

Thanks much for reporting!
-KenD

**Comment by rcpacheco** [comment]
The update fixed this issue also. Thanks a lot!!

**Comment by rcpacheco** [comment]
Hello Ken, sorry for asking in a closed issue. But after watching your video Color 2 UI part 2 (5:05) related to this topic, dragging objects from the menu, I see that you take the borderWith number from a Morph and although you get a red X while trying to drop the number on top of the color value, you are able to place it on top of the color  as a box with the number and leave it there for a seconds while you move the mouse and then pick it up again an you place it in the  desktop, before deleting it. In the current implementation I tested after this change, it only presents the red X but the number disappears and is not placed on top of the color. Is that the expected behavior or should I reopen this issue? I find really nice the possibility to place the number somewhere else as a LabelMorph. Could be very useful in some cases.

**Comment by KenDickey** [comment]
This is a change.  I found that only allowing drops on fields willing to accept the value (color/number/font/point/..) more consistent and, frankly, easier to implement.  I want things to be useful, but the "drop onto backdrop" did not buy me much, and where does one stop.  E.g. drop a DropColorMorph directly on some random Morph vs dropping only on Color fields in a Morph's menu.
Now a SignMorph has the same behavior as a FontMorph or a DropColorMorph with respect to Drag 'n Drop.

I did not want to torque the code for Morphs.  That is why there is a "Drop Target" available, to be an intermediary between a Morph and some tool-ish action.  If you drop a color onto a DropTarget, it asks how to treat the color.  You can change the color, borderColor, .. or pass.  No Morph code was harmed by this. ;^)

Another user interface problem I had was to make things which _are_ different actually _look_ different.  This is why there is a purple border around dragable color swatches and why visual properties which one can drag are purple.

HTH, -KenD

**Comment by rcpacheco** [comment]
Yes, you are right. It Is  easy to forget where to stop. Since simple is beautiful, I find reasonable your decision. Thanks for your response. 

Richo

**Comment by KenDickey** [comment]
Play is important.
When I get ideas, I like to try to get them ruunning in code -- so I learn with failure and gain confidence with success.
One way to learn is to imagine a different way and try to make the code do that.
I found Drag 'n Drop hard, so I try to make something helpful with this.
If you make draggable properties stick to desk top, I guarantee you will learn a lot!  :)
