### ISSUE TITLE
Property edit window not reused

### ISSUE THREAD

**Issue by rcpacheco** [Cuis-Smalltalk/Cuis-Smalltalk-UI#73]
Most likely this is not a bug, but it seems to me that it does not make sense to open a new edit window each time the same property is clicked for edit. Maybe it would be enough to bring any other previous edit window to the front, in case it got hidden by other Morphs in the display. But not a new window every time I hit the property.

![image](https://user-images.githubusercontent.com/845725/206689056-f3fd6415-8f3e-498e-92c1-b5eb4c4188c6.png)

**Comment by KenDickey** [comment]
On 2022-12-09 03:12, Ricardo Pacheco wrote:

> Most likely this is not a bug, but it seems to me that it does not make 
> sense to open a new edit window each time the same property is clicked 
> for edit. Maybe it would be enough to bring any other previous edit 
> window to the front, in case it got hidden by other Morphs in the 
> display. But not a new window every time I hit the property.

This is a tough call, but it seems to me that every time you ask for a 
new window or panel you should get one.

   World Menu -> Windows -> Find Window

is your friend..

-KenD

**Comment by rcpacheco** [comment]
I buy it. Thanks a lot for the tip!
