### ISSUE TITLE
Cuis-Smalltalk-UI morphs are not working

### ISSUE THREAD

**Issue by ivsukin** [Cuis-Smalltalk/Cuis-Smalltalk-UI#74]
I'm trying to follow the examples in The Cuis Book, but have some problems with Cuis-Smalltalk-UI morphs. I'm running Cuis on Windows 11 x64 and Cog Spur VM.

**Steps to reproduce:**
1. Install Cuis and Cog using [this](https://github.com/Cuis-Smalltalk/Cuis-Smalltalk-Dev/blob/master/Documentation/GettingStarted.md) instruction.
2. Install Cuis-Smalltalk-UI using ```Feature require: 'UI-Shapes'``` from Workspace.
3. Create an EllipseMorph.
4. Create a BoxedMorph
5. Middle-click on an EllipseMorph to show halo OR try to embed BoxedMorph using menu button from halo.

**Expected behaviour**

Everything working correctly

**Actual behaviour**

1. Transcript shows the following:
```
Package UI-Shapes successfully installed
Undeclared: a Dictionary(#MetaProperty->nil #VisualPropertyMenuItem->nil )

```
2. Halo on Cuis-Smalltalk-UI does not appear.
3. Attempt to show menu for a BoxedMorph raises an error (see below), but only if there was at least on morph from Cuis-Smalltalk-UI created.

![2023-07-16_17-16-34](https://github.com/Cuis-Smalltalk/Cuis-Smalltalk-UI/assets/23117090/b3781925-bfd8-4d90-a18c-e2cb77fc5862)

**Comment by KenDickey** [comment]
Thanks much for the report!
There was a change with Vector Graphics which now requires EllipseMorph to implement #requiresVectorCanvas.
Please retest to be sure this fixes your problem.

Also, I updated the control handle icons of some vector graphic shapes to eliminate dependency on icons in the VisualPropertyMenuItem class.

The unbound reference to `MetaProperty` is harmlessly protected with guards:
	(Smalltalk includesKey: #MetaProperty )
		ifTrue: [ self initializeMetaProperties ].

**Comment by ivsukin** [comment]
Thank you very much, now it is working as intended!
